name: Test Github Actions variable-04
run-name: Test Github Actions variable-04
on:
   workflow_dispatch:
    inputs:
      name:
        description: '이름'
        required: true
        default: 'Input'
    
jobs:
  input-data:
    runs-on: ubuntu-latest
    steps:
      - name: print input data
        run: echo "Hello, ${{ github.event.inputs.name }}"
      
