name: Test Github Actions variable-03
run-name: Test Github Actions variable-03
on:
   workflow_dispatch

jobs:
  check-vars-context:
    runs-on: ubuntu-latest
    steps:
      - name: "Hello, ${{ vars.var_test }}"
    
