name: Test Github actions checkout-01
run-name: Run Github actions checkout
on:
  workflow-dispatch

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: action ls
        run: ls -al
        
      - name: github actions checkout
        uses: actions/checkout@v4
        with:
          path: checkout-dir
      - name: github actions checkout
        uses: actions/checkout@v4
        with:
          repository: actions/checkout
          path: other-repo
      - run : ls -al 
